name: DungeonBe
version: 1.0-pre
main: SkulZOnTheYT\DungeonBe\DBMain
api: 5.0.0
depend: BedrockEconomy
softdepend: MaskUI
author: SkulZOnTheYT

commands:
  dungeon:
     description: Main command DungeonBe
     alliases: 
     - dngn
     - dgn
     - dg
     permission: dungeonbe.main-command

permission:
  dungeonbe.main-command:
     description: permission Main command DungeonBe
     default: true
